status = [
    "Build",
    "Lint",
]
required_approvals = 1
up_to_date_approvals = true
delete_merged_branches = true
update_base_for_deletes = true
use_codeowners = true
cut_body_after = "<details>"
