[package]
name = "runst"
description = "A dead simple notification daemon"
authors = ["Orhun Parmaksız <orhunparmaksiz@gmail.com>"]
license = "MIT OR Apache-2.0"
version = "0.1.0"
edition = "2021"

[dependencies]
dbus = "0.9.6"
dbus-crossroads = "0.5.1"
x11rb = { version = "0.10.1", default-features = false, features = ["allow-unsafe-code"] }
cairo-rs = { version = "0.15.12", default-features = false, features = ["use_glib", "xcb"] }
pango = "0.15.2"
pangocairo = "0.15.1"
thiserror_lite = "0.1.0"
serde = { version = "1.0.140", features = ["derive"] }
toml = "0.5.8"
sscanf = "0.3.1"
colorsys = "0.6.6"
tinytemplate = "1.2.1"
dirs = "4.0.0"

[build-dependencies]
dbus-codegen = "0.10.0"
