[package]
name = "runst"
description = "A dead simple notification daemon"
authors = ["Orhun Parmaksız <orhunparmaksiz@gmail.com>"]
license = "MIT OR Apache-2.0"
version = "0.1.0"
edition = "2021"

[dependencies]
dbus = "0.9.5"
thiserror_lite = "0.1.0"
