[global]
    geometry = "1920x23+0+0"
    font = "Monospace 10"
    format = "[{app_name}] <b>{summary}</b> {body}"

[urgency_low]
    background = "#000000"
    foreground = "#505050"
    timeout = 10
    text = "low"

[urgency_normal]
    background = "#000000"
    foreground = "#aaaaaa"
    timeout = 10
    text = "normal"

[urgency_critical]
    background = "#000000"
    foreground = "#ffffff"
    timeout = 0
    text = "critical"
    custom_commands = [ 'gotify push -t "{app_name}" "{summary}" > /dev/null' ]
